JUnit test AddLifeInsuranceCommandTest and utility class LifeInsuranceBuilder
CS2103AUG2017-T13-B1/main pull request #169
Opened 2017-11-11 20:37 UTC by OscarWang114

Changes:
- Every field of  `LifeInsurance` is now a unique class of itself. Please refer to the last section.
- Refactor of constructor of `LifeInsurance`
- Name field of `InsurancePerson` is now a `Name` instead of a `String`
- Created JUnit test `AddLifeInsuranceCommandTest` and utility class `LifeInsuranceBuilder`

New type of fields in `LifeInsurance` :
- `InsuranceName` for the name of insurance, regex only accepts alphanumeric letters and cannot be blank.
- `Premium` for premium, regex only accepts numbers and one optional decimal point.
-`ContractFileName` for the name of the contract file, accepts alphanumeric letters, hyphens, underscores, and cannot be blank.

2017-11-11 21:35 UTC, OscarWang114 commented
81 percent!!!!!!

2017-11-12 02:11 UTC, Juxarius requested changes
LGTM

only change u need is to change the li tag in UserGuide.adoc to addli
cos currently its wrong and you are tagging nothing
asciidoctor also keeps giving warning for this

2017-11-12 02:11 UTC, Juxarius commented on data/addressbook.xml
> +                <contractFileName>NotInLisa-Expensive.pdf</contractFileName>
lol i knew this change was coming

2017-11-12 02:11 UTC, Juxarius commented on src/main/java/seedu/address/logic/parser/AddCommandParser.java
>              ReadOnlyPerson person = new Person(name, phone, email, address, dob, gender, tagList);
why are we putting as final again? defensive programming?

2017-11-12 02:11 UTC, Juxarius commented on src/main/java/seedu/address/model/insurance/LifeInsurance.java
>          this.id = new SimpleObjectProperty<>(source.idProperty().get());
haha didnt think of this method, good job

2017-11-12 02:11 UTC, Juxarius commented on src/main/java/seedu/address/model/insurance/LifeInsurance.java
> +    public void setSigningDateString(String signingDateString) {
consider making this private?

2017-11-12 02:11 UTC, Juxarius commented on src/main/java/seedu/address/model/insurance/InsurancePerson.java
> +    public InsurancePerson(String nameString) throws IllegalValueException {
Just wanted to say "Told ya~"

2017-11-12 07:38 UTC, OscarWang114 commented on src/main/java/seedu/address/logic/parser/AddCommandParser.java
>              ReadOnlyPerson person = new Person(name, phone, email, address, dob, gender, tagList);
That is what I initially thought. But now I don't think it makes much meaning to use `final` here.

2017-11-12 07:38 UTC, OscarWang114 commented on src/main/java/seedu/address/model/insurance/LifeInsurance.java
> +    public void setSigningDateString(String signingDateString) {
Yes will do

2017-11-12 09:24 UTC, Juxarius approved these changes

2017-11-12 09:25 UTC, merged